### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by angelroma** [angelroma/Finance-App-Website#1]
Create a component footer.

**Comment by ELiusq** [comment]
Hare el Footer

**Comment by angelroma** [comment]
@ELiusq Es todo tuyo. Solo estamos haciendo el maquetado en HTML no necesitamos estilos por el momento.

**Comment by ELiusq** [comment]
ok

**Comment by ELiusq** [comment]
Ya instale por completo todo lo que hiciste en el Tutorial

**Comment by angelroma** [comment]
@ELiusq  Cuando termines espero tu pull request para hacer review de tu desarrollo.

**Comment by angelroma** [comment]
@ELiusq  Our Footer has html markup only, WE NEED STYLES NOW!!!
It's time to add styles to out navigation following these rules.

[references about flex](https://www.w3schools.com/css/css3_flexbox.asp)
[example](https://www.w3schools.com/css/tryit.asp?filename=trycss3_flexbox_website2)
Try to understand the difference between FLOAT, FLEX and GRID, so let's go to YOUTUBE!!

1. Responsive and mobile friendly
2. With 100%
3. Colors are up to you
4. We are using Flex properties and not FLOAT or GRID

**Comment by ELiusq** [comment]
Ok Boss.

**Comment by ELiusq** [comment]
Boss, but I don't have anything like i can use with Flex...
All things in HTML are only links.
Unless do you want to use flex in the container..
