### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by angelroma** [angelroma/Finance-App-Website#3]
Create a component for a Home page.

To be included in the home page 
1.- App description and characteristics

**Comment by E-Mauro** [comment]
Yo hago la home page !

**Comment by angelroma** [comment]
@E-Mauro Vale, ya lo tienes asignado.
Crearas un componente llamado HomePage, crea una nueva rama para esto, dudas me envías mensaje.

**Comment by E-Mauro** [comment]
I added the HomePage module, could you check if it is correct?
if so, i'll add more content to it

**Comment by angelroma** [comment]
There you go @E-Mauro , Let's add some content, you can get some ideas here: [IDEAS](https://www.landingfolio.com/category/gallery/mobile-app/).
Also, keep your styles local to your component (HomePage.css) and not the the whole website (index.css)

**Comment by angelroma** [comment]
@E-Mauro  We will need to create styles for our home page view. So I've updated the issue.
[References and example](https://www.w3schools.com/css/tryit.asp?filename=trycss3_flexbox_website2)

- [ ]  Add styles to your HomePage compatibles with flexbox so it can be responsive.
